name: Build and Deploy
on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          
          script: |
            rm -r janet-main
            wget https://github.com/richarditokazo/janet/archive/refs/heads/main.zip
            unzip main.zip
            rm main.zip
            cp .env janet-main/v2/src      
            nvm use 16      
            cd janet-main && npm install
            cd v2/src
            pm2 delete 0
            pm2 start index.js            
            echo 'Deployment Done'
